fix: fixed "AttributeError: 'NoneType' object has no attribute 'type'"
* The error started appearing after commit f9a3568.

https://github.com/CertiKProject/slither-task/issues/71